# Generated by Django 5.2.8 on 2025-11-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, to='core.disciplinas', verbose_name='Pré-requisitos'),
        ),
    ]
