# Generated by Django 5.2.7 on 2025-10-22 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 10, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='status',
            field=models.CharField(choices=[('APR', 'Aprovado'), ('CANC', 'Cancelado'), ('CUMP', 'Cumpriu'), ('DISP', 'Dispensado'), ('MATR', 'Matriculado'), ('REP', 'Reprovado por média'), ('REPF', 'Reprovado por falta'), ('REPMF', 'Reprovado por média e falta'), ('TRANC', 'Matrícula trancada')], max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3),
        ),
    ]
