# Generated by Django 5.2.8 on 2025-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_disciplinas_pre_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizcurricular',
            name='curso',
            field=models.CharField(choices=[('Sistemas de Informação', 'Bacharelado em Sistemas de Informação'), ('Ciência da Computação', 'Ciência da Computação'), ('Engenharia de Software', 'Engenharia de Software'), ('Análise e Desenv. de Sistemas', 'Análise e Desenv. de Sistemas'), ('Licenciatura em Matemática', 'Licenciatura em Matemática')], max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_usuarios', related_query_name='core_usuario', to='auth.group', verbose_name='Grupos de Usuário'),
        ),
    ]
