# Generated by Django 5.2.8 on 2025-11-17 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analise', models.CharField(choices=[('padrao', 'Padrão'), ('soft', 'Soft'), ('hard', 'Hardcore')], max_length=10)),
                ('dias_excluidos', models.CharField(blank=True, help_text="Ex: 'SEG,TER'", max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('resultado_texto', models.TextField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='upload.historico')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=3)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='analytics.analise')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplinas')),
            ],
        ),
    ]
