# Generated by Django 5.2.8 on 2025-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analise', models.CharField(choices=[('padrao', 'Padrão'), ('soft', 'Soft'), ('hard', 'Hardcore')], max_length=10)),
                ('dias_excluidos', models.CharField(blank=True, help_text="Ex: 'SEG,TER'", max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('resultado_texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=3)),
                ('periodo', models.CharField(max_length=10)),
            ],
        ),
    ]
