# Generated by Django 5.2.8 on 2025-11-23 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='historico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='upload.historico'),
        ),
        migrations.AddField(
            model_name='analiseitens',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='analytics.analise'),
        ),
        migrations.AddField(
            model_name='analiseitens',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplinas'),
        ),
    ]
