# Generated by Django 5.2.8 on 2025-11-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analiseitens',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='analiseitens',
            name='horario_inicio',
        ),
        migrations.AddField(
            model_name='analiseitens',
            name='periodo',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
