# Generated by Django 5.2.8 on 2025-11-23 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('curso', models.CharField(max_length=100, verbose_name='Curso de Ingresso')),
                ('ano_ingresso', models.CharField(max_length=6, verbose_name='Ano de Ingresso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'ALUNO',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('status', models.CharField(choices=[('PENDENTE', 'Processamento Pendente'), ('CONCLUIDO', 'Processamento Concluído'), ('ERRO', 'Erro no Processamento')], default='PENDENTE', max_length=20, verbose_name='Status de Processamento')),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to='historicos/', verbose_name='Arquivo PDF Original')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='upload.aluno', verbose_name='Aluno')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Coordenador Responsável')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
                'db_table': 'HISTORICO',
            },
        ),
        migrations.CreateModel(
            name='HistoricoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=200, verbose_name='Nome da Disciplina')),
                ('disciplina_sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('ch', models.IntegerField(verbose_name='Carga Horária')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frequencia', models.IntegerField(blank=True, null=True, verbose_name='Frequência (%)')),
                ('status_disciplina', models.CharField(max_length=50, verbose_name='Situação')),
                ('semestre_cursado', models.CharField(max_length=10, verbose_name='Semestre Cursado')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='upload.historico', verbose_name='Histórico')),
            ],
            options={
                'verbose_name': 'Item de Histórico',
                'verbose_name_plural': 'Itens de Histórico',
                'db_table': 'HISTORICO_ITENS',
            },
        ),
    ]
